services:
  power-meter-reader:
    image: power-meter-reader:latest
    build:
      context: ./src
      dockerfile: dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
      
  # # # take logs from power-meter-reader and send to Loki
  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ./promtail-config.yaml:/etc/promtail/config.yaml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: -config.file=/etc/promtail/config.yaml
  #   depends_on:
  #     - power-meter-reader
  #   restart: always