{
 "title": "power-meter-influxdb",
 "tags": [ "promtail" ],
 "time": { "from": "now-30h", "to": "now-25h" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "VOLTAGE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "CURRENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "apparent power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "APPARENT_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "active power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "ACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "reactive power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "REACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "power factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "POWER_FACTOR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "FREQUENCY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "VOLTAGE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "CURRENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kilowatt-hour",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "query": "SELECT difference(last(\"KILOWATT_HOURS\")) FROM \"power_meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "KILOWATT_HOURS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "ACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "INFO" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "APPARENT_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "REACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "power histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "ACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "APPARENT_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "REACTIVE_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kilowatt-hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "query": "SELECT mean(\"KILOWATT_HOURS\") FROM \"power_meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "KILOWATT_HOURS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "TEMPERATURE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KWS-AC301 reader system log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "power_meter",
     "query": "SELECT \"MESSAGE\", \"DATA\", \"level\"::tag FROM \"power_meter\" WHERE $timeFilter GROUP BY \"level\"::tag",
     "select": [
      [
       { "params": [ "DATA" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "!=", "value": "INFO" }
     ]
    }
   ]
  },
  {
   "title": "Log level percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "alias": "INFO",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"SAMPLE_RATE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'INFO') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "DEBUG",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'DEBUG') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "WARN",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'WARN') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "ERROR",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'ERROR') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "FATAL",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'FATAL') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    }
   ]
  },
  {
   "title": "sample rate",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "SAMPLE_RATE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log level count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "INFO",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"SAMPLE_RATE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'INFO') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "DEBUG",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'DEBUG') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "WARN",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'WARN') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "ERROR",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'ERROR') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    },
    {
     "alias": "FATAL",
     "groupBy": [
      { "params": [ "level::tag" ], "type": "tag" }
     ],
     "measurement": "power_meter",
     "query": "SELECT count(\"MESSAGE\") FROM \"power_meter\" WHERE  (\"level\"::tag = 'FATAL') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "MESSAGE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "level::tag", "operator": "=", "value": "DEBUG" }
     ]
    }
   ]
  },
  {
   "title": "elapsed time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "ELAPSED_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "system time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  }
 ]
}