server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.1.100:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep

      - source_labels: [__meta_docker_container_label_logging_job]
        target_label: job

      - source_labels: [__meta_docker_container_name]
        target_label: container
        
    pipeline_stages:
      - json:
          expressions:
            LEVEL: LEVEL
            TIMESTAMP: TIMESTAMP
      - timestamp:
          source: TIMESTAMP
          format: UnixNs
